# Generated by Django 3.2 on 2021-04-26 08:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='field',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='field'),
        ),
        migrations.AddField(
            model_name='test',
            name='field_desc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='field_desc'),
        ),
        migrations.AddField(
            model_name='test',
            name='tag',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='test',
            name='tag_desc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='tag_desc'),
        ),
    ]
