# Generated by Django 3.2 on 2021-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20210426_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='db_name',
            field=models.CharField(max_length=255, null=True, verbose_name='数据库名'),
        ),
        migrations.AddField(
            model_name='test',
            name='table_name',
            field=models.CharField(max_length=255, null=True, verbose_name='表名'),
        ),
    ]
